add starttls
TwinProduction/gatus pull request #120
Opened 2021-06-03 18:10 UTC by gopher-johns

Hello,
Thank you for your great tool. I wanted to test some SMTP servers so I added a few lines of codes.

Regards.

GJ

2021-06-04 00:11 UTC, TwinProduction requested changes

2021-06-04 06:36 UTC, gopher-johns commented on config.yaml
> +      - "[CERTIFICATE_EXPIRATION] > 48h"
I removed that part. :+1:

2021-06-05 19:46 UTC, TwinProduction commented
Looks good, thank you for your contribution @gopher-johns!

2021-06-05 19:47 UTC, merged

2021-06-18 13:57 UTC, TwinProduction commented
Released in [v2.7.0](https://github.com/TwinProduction/gatus/releases/tag/v2.7.0)